### ISSUE TITLE
Projeto para sala do sigilo do IBGE

### ISSUE THREAD

**Issue by lucasmation** [lucasmation/BrasilMais#3]
@felipefb-barros, 

precisamos escrever um projeto para acesso de dados na sala do sigilo do IBGE para auxiliar nas avaliações do Brasil Mais Produtivo, Brasil + e InovAtiva. Você poderia ajudar a escrever a 1a versão?

Para isso você pode se basear em:
- Pre Analisys plan que escrevemos para o B+P: [LowCost_LeanManuf_RCT_Brazil_PAP.pdf](https://github.com/lucasmation/BrasilMais/files/8125182/LowCost_LeanManuf_RCT_Brazil_PAP.pdf)
- Projeto de tabulação especial que mandamos pra Receita: [Parceria RFB - Avaliação impacto B+ InovAtiva Pronampe - 31.05.2021 _v6.docx](https://github.com/lucasmation/BrasilMais/files/7635768/Parceria.RFB.-.Avaliacao.impacto.B%2B.InovAtiva.Pronampe.-.31.05.2021._v6.docx)
- [GUIA DO USUÁRIO DA SALA DE ACESSO A DADOS RESTRITOS (SAR)](https://www.ibge.gov.br/images/pdf/acessoinformacao/guia_do_usuario_da_sala_de_acesso_a_dados_restritos.pdf)

Pro IBGE, não importa muito a motivação dos estudos. Pode ser poucas linhas para cada, como esta no projeto da Receita, ou ate mais sucinto. Vai ser lido por analistas de dados / estatísticos. O importante e' que os planos tabulares, ou tabelas de regressão estejam bem claros. 

Como você vera no projeto da Receita, a ideia e' tratar os 3 estudos como se fossem estratos de um grande estudo. 
Entao vai ter T1 = tratados do estudo A, T2 = tratados do estudo B, ...., C1= controles do estudo A, C2= controles do estudo B, etc... 
Desta forma você pode pedir os resultados para todos os estudos numa tabela só (claro que as subdivisões podem ser ainda maiores, com subdivisoes regionais, setoriais, ou de extratos de fato dentro de cada um destes estudos). Mas o ponto e' para ilustrar como da para pedir uma tabela só contendo estatísticas para vários estudos 

Outra questão importante para se ter em mente e' que muitos destes programas foram em empresas relativamente pequenas que so aparecerão no estrato aleatório da pesquisa. Precisa pensar em como isso afetaria e fazer uma proposta que leve isso em consideração. 

Favor elaborar um 1o draft que depois depuramos juntos.

**Comment by felipefb-barros** [comment]
@lucasmation Escrevi um primeiro draft. Nele você vai encontrar todos os campos que são obrigatórios estarem contidos no documento. O documento foi muito baseado no da RFB. Fiquei com dúvida em algumas coisas:
1 - As variáveis e resultados a serem solicitados.
2 - Uso de bases externas? (Se sim teremos que preencher tambem um documento de autorização do uso dos dados externos)

Conforme for sanando as dúvidas irei modificando o documento incorporando as melhorias. 

[PROJETO_IBGE.pdf](https://github.com/lucasmation/BrasilMais/files/8197463/PROJETO_IBGE.pdf)

**Comment by lucasmation** [comment]
Felipe, obrigado.

bom avanco.

Feedback:
- E` necessario listar as bases do IBGE que serao usadas. PIA-Empresa,
PIA-Produto
- A PIA-empresa tem faturamento apenas anual.
- E` necessario considerar como o plano amostral da PIA-Empresa e
PIA-Produto afetam nossas estimativas. Vamos ter que quebrar nossa amostra
entre empresas do estrato certo e do estrato aleatorio da PIA.

1) Quais variaveis usar: tem que olhar um pouco em paper similares feitos
no Brasil para ver o que as pessoas usam (avaliacoes da lei da informatica,
do BNDES, etc que usarm a sala do sigilo). Ate onde me lembro o pessoal usa
o valor bruto da producao industrial. Pela PIA-produto haveria tabem
quantidades, mas nao sei se empresas deste porte respoondem a PIA produto.
2) Sim, podemos trazer. O que vamos trazer sao os dados do programa em si
(estratos, Z (dummy para grupo de tratado), D (dummy para participante no
programa), indicadores de resposta aos questionarios) e dados da RAIS.

por favor atualize os projetos com base neses esclarecimentos e podemos
falar mais tarde na semana, ok?




Em seg., 7 de mar. de 2022 às 06:00, felipefb-barros <
***@***.***> escreveu:

**Comment by lucasmation** [comment]
@felipefb-barros 

- O plano amostral da PIA pode ser encontrado [nesta nota tecnica](https://biblioteca.ibge.gov.br/visualizacao/periodicos/1719/pia_2019_v38_n1_empresa_notas_tecnicas.pdf) e também [nesta página](https://www.ibge.gov.br/estatisticas/economicas/industria/9042-pesquisa-industrial-anual.html?=&t=conceitos-e-metodos). 
- Existem documentos similares para PAS, PAC. 
- tabela 1: substituir ano-mes por ano. Adicionar uma coluna "Estrato IBGE (aleatório/certo)"
- precisamos de uma tabela adicional explicando o atrito (empresas que se recusaram a responder) no nosso Q2. Ainda nao esta claro pra mim qual seria analise para isso. Precisamos pensar nisso
- Precisamos tb tentar prever, pelos questionários que aplicamos no B+P, quais empresas estarao ou nao na PIA. Vou lancar um issue separado sobre isso.
